### ISSUE TITLE
Cannot import encoder in sman.py.

### ISSUE THREAD

**Issue by liqimai** [nhhoang96/Semantic_Matching#1]
`sman.py` imports `encoder` at line 10, but there is no `encoder.py` in this repo, and it also seems not matching any public encoder package.
```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    import sman
  File "/Users/liqimai/workspace/Semantic_Matching/code/sman.py", line 10, in <module>
    import encoder
ModuleNotFoundError: No module named 'encoder'
```

**Comment by nhhoang96** [comment]
Thank you for spotting the issue. The latest push should resolve the issue. Please pull the whole repository again since changes are also made to other files to reduce confusion and redundancy. 
Additional documentation on how to run the code is also updated on README.  Please feel free to let me know if the problem persists.

**Comment by liqimai** [comment]
Thanks very much for your fast fix. I can run it now.😸👍
